package cse360pro1;

import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 * Initial GUI displayed when program starts.
 * Prompts the user to choose 4 players to start a game.
 * @author Michael
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
    }

    /**
     * Updates the list of players in the dropdown based on prior stats.
     */
    private void updatePlayerList() {
		ArrayList<String> playerNameList = Database.getSingleton().getAllPlayerNames();
        String[] playerNameArray = playerNameList.toArray(new String[playerNameList.size()]);
        JComboBox[] comboBoxes = {
            player1Combo,
            player2Combo,
            player3Combo,
            player4Combo,
        };
        for (int index = 0; index < 4; index++) {
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<String>(playerNameArray);
            model.setSelectedItem("");
            comboBoxes[index].setModel(model);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        playerListPanel = new javax.swing.JPanel();
        player1Label = new javax.swing.JLabel();
        player1Combo = new javax.swing.JComboBox<>();
        player2Label = new javax.swing.JLabel();
        player2Combo = new javax.swing.JComboBox<>();
        player3Label = new javax.swing.JLabel();
        player3Combo = new javax.swing.JComboBox<>();
        player4Label = new javax.swing.JLabel();
        player4Combo = new javax.swing.JComboBox<>();
        buttonPanel = new javax.swing.JPanel();
        startGameButton = new javax.swing.JButton();
        rulesButton = new javax.swing.JButton();
        statsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dice Simulator 2016");

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logov1a.png"))); // NOI18N
        getContentPane().add(titleLabel, java.awt.BorderLayout.NORTH);

        playerListPanel.setLayout(new java.awt.GridLayout(0, 2));

        player1Label.setText("Player 1");
        playerListPanel.add(player1Label);

        player1Combo.setEditable(true);
        playerListPanel.add(player1Combo);

        player2Label.setText("Player 2");
        playerListPanel.add(player2Label);

        player2Combo.setEditable(true);
        playerListPanel.add(player2Combo);

        player3Label.setText("Player 3");
        playerListPanel.add(player3Label);

        player3Combo.setEditable(true);
        playerListPanel.add(player3Combo);

        player4Label.setText("Player 4");
        playerListPanel.add(player4Label);

        player4Combo.setEditable(true);
        playerListPanel.add(player4Combo);

        getContentPane().add(playerListPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.GridLayout(0, 1));

        startGameButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startGameButton.setText("Start game");
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(startGameButton);

        rulesButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rulesButton.setText("Rules");
        rulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(rulesButton);

        statsButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        statsButton.setText("Stats");
        statsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(statsButton);

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(exitButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles Start game button click.
     * @param evt Associated event.
     */
    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
		String[] names = {
            player1Combo.getSelectedItem().toString(),
            player2Combo.getSelectedItem().toString(),
            player3Combo.getSelectedItem().toString(),
            player4Combo.getSelectedItem().toString()
		};

		boolean badPlayerName = false;
		for (int index = 0; !badPlayerName && index < names.length; index++)
		{
			if (!Database.isNameValid(names[index]))
			{
				JOptionPane.showMessageDialog(this, "\"" + names[index] + "\" is not a valid player name");
				badPlayerName = true;
			}
			for (int duplicateIndex = 0; !badPlayerName && duplicateIndex < index; duplicateIndex++)
			{
				if (names[duplicateIndex].equals(names[index]))
				{
					JOptionPane.showMessageDialog(this, "Cannot have duplicate names");
					badPlayerName = true;
				}
			}
		}

		if (!badPlayerName)
		{
			GameGui gui = new GameGui(this);
			Controller model = new Controller(
				names[0],
				names[1],
				names[2],
				names[3]
			);
			model.setGameGui(gui);
			gui.setModel(model);
			setVisible(false);
			gui.setVisible(true);
		}
    }//GEN-LAST:event_startGameButtonActionPerformed

    /**
     * Handles Exit button click.
     * @param evt Associated event.
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * Handles Rules button click.
     * @param evt Associated event.
     */
    private void rulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesButtonActionPerformed
        JDialog dialog = new JDialog(this, "Rules");
        RulesGuiPanel panel = new RulesGuiPanel();
        dialog.getContentPane().add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_rulesButtonActionPerformed

    /**
     * Handles Stats button click.
     * @param evt Associated event.
     */
    private void statsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsButtonActionPerformed
        JDialog dialog = new JDialog(this, "Statistics");
        StatsGuiPanel panel = new StatsGuiPanel();
        dialog.getContentPane().add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_statsButtonActionPerformed
    
    
    /**
     * Main entry point of the program.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainGui gui = new MainGui();
                gui.setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JComboBox<String> player1Combo;
    private javax.swing.JLabel player1Label;
    private javax.swing.JComboBox<String> player2Combo;
    private javax.swing.JLabel player2Label;
    private javax.swing.JComboBox<String> player3Combo;
    private javax.swing.JLabel player3Label;
    private javax.swing.JComboBox<String> player4Combo;
    private javax.swing.JLabel player4Label;
    private javax.swing.JPanel playerListPanel;
    private javax.swing.JButton rulesButton;
    private javax.swing.JButton startGameButton;
    private javax.swing.JButton statsButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
